### PR TITLE
use keysm instead of keycode for more cross platform compatibility

### PR DESCRIPTION
**Pull request by lentferj**

### CODE REVIEW

**Comment by NilsKr** [comment]
Sorry, I committed my own change before seeing that there was a pull request with the same changes :-(

**Comment by lentferj** [comment]
no problem

**Comment by NilsKr** [comment]
While we are here, what is the convention for closing issues? Is this generally done by the reporter of the issue after confirming the fix is ok?

**Comment by lentferj** [comment]
well, I think that is basically up to you, but good practice would be to let the reporter confirm the fix works and then close the ticket (either yourself or the reporter) or close it after a certain period, when the original reporter does not come back with a confirmation - which also happens quite a bit, unfortunately.

**Pull request closed without merging**
